/**
 * Asset registration for kiosk-keyboard-webc.
 *
 * Registers theme parameter bundles and i18n loaders with the UI5 Web Components
 * framework. Import this module before using the component to ensure themes and
 * translations are available at runtime.
 *
 * Generated by `@ui5/webcomponents-tools` from:
 *   - CSS: `src/themes/KioskKeyboard.css` → component styles
 *   - Themes: `src/themes/{theme}/parameters-bundle.css` → per-theme variables
 *   - i18n: `src/i18n/messagebundle*.properties` → locale bundles
 *
 * Run `npm run generate` to regenerate after editing source CSS or .properties files.
 *
 * @module Assets
 */

// Register global SAP theme variable loaders (--sapButton_Background, --sapBackgroundColor, etc.)
// Without this import, theme switching (e.g. sap_horizon_dark) has no effect because the
// global CSS custom properties that the component CSS references stay at their default values.
import "@ui5/webcomponents-theming/dist/Assets.js";

// Register i18n locale loaders (generated from src/i18n/messagebundle_*.properties)
import "./generated/json-imports/i18n.js";

// Register theme parameter bundle loaders (generated from src/themes/*/parameters-bundle.css)
import "./generated/json-imports/Themes.js";

// Load the SAP "72" font-face declarations. The component CSS references "72" as the
// primary font-family; without this import the browser falls through to Arial whose
// wider glyph metrics can cause visible clipping on narrow keys (e.g. phone viewports).
// When OpenUI5 is detected this is a no-op since the framework loads the font itself.
import insertFontFace from "@ui5/webcomponents-base/dist/FontFace.js";

insertFontFace();

// Fetch the i18n bundle (async, fire-and-forget - texts use English defaults until loaded)
import { initI18n } from "./core/i18n.js";

void initI18n();
