/**
 * Asset registration for kiosk-keyboard-webc.
 *
 * Registers theme parameter bundles and i18n loaders with the UI5 Web Components
 * framework. Import this module before using the component to ensure themes and
 * translations are available at runtime.
 *
 * Generated by `@ui5/webcomponents-tools` from:
 *   - CSS: `src/themes/KioskKeyboard.css` → component styles
 *   - Themes: `src/themes/{theme}/parameters-bundle.css` → per-theme variables
 *   - i18n: `src/i18n/messagebundle*.properties` → locale bundles
 *
 * Run `npm run generate` to regenerate after editing source CSS or .properties files.
 *
 * @module Assets
 */

// Register i18n locale loaders (generated from src/i18n/messagebundle_*.properties)
import "./generated/json-imports/i18n.js";

// Register theme parameter bundle loaders (generated from src/themes/*/parameters-bundle.css)
import "./generated/json-imports/Themes.js";

// Fetch the i18n bundle (async, fire-and-forget - texts use English defaults until loaded)
import { initI18n } from "./core/i18n.js";

void initI18n();
