export {
  GLOBAL_SCOPE,
  MODIFIER_KEYS,
  MODIFIER_ORDER,
  MODIFIER_ALIASES,
  KEY_ALIASES,
  MAC_MODIFIER_SYMBOLS,
  STANDARD_MODIFIER_LABELS,
  KEY_DISPLAY_SYMBOLS,
  normalizeKeyName,
} from "./internal/constants";
